# Generated by Django 3.1.5 on 2021-01-30 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldproj',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='documentation.employee', verbose_name='RESPONSÁVEL'),
        ),
        migrations.AlterField(
            model_name='ldproj',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.statusdoc', verbose_name='STATUS'),
        ),
    ]
