# Generated by Django 3.1.5 on 2021-02-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_auto_20210129_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldproj',
            name='aprov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprov', to='documentation.employee', verbose_name='APROVADOR'),
        ),
        migrations.AlterField(
            model_name='ldproj',
            name='elab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elab', to='documentation.employee', verbose_name='ELABORADOR'),
        ),
        migrations.AlterField(
            model_name='ldproj',
            name='emiss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emiss', to='documentation.employee', verbose_name='EMISSOR'),
        ),
        migrations.AlterField(
            model_name='ldproj',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='documentation.employee', verbose_name='RESPONSÁVEL'),
        ),
        migrations.AlterField(
            model_name='ldproj',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.statusdoc', verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='ldproj',
            name='verif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verif', to='documentation.employee', verbose_name='VERIFICADOR'),
        ),
    ]
