# Generated by Django 3.1.5 on 2021-02-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20210210_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldproj',
            name='qt_page',
        ),
    ]
