# Generated by Django 3.1.7 on 2021-03-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_remove_ldproj_qt_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvalue',
            name='cost_by_A1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CUSTO A1 EQ'),
        ),
        migrations.AlterField(
            model_name='projectvalue',
            name='cost_by_doc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CUSTO FOLHA'),
        ),
        migrations.AlterField(
            model_name='projectvalue',
            name='cost_by_hh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CUSTO HH'),
        ),
    ]
