# Generated by Django 4.0 on 2022-01-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=12, verbose_name='AÇÃO')),
                ('created_st', models.DateTimeField(auto_now_add=True)),
                ('update_st', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(max_length=5, verbose_name='TIPO DE DOCUMENTO')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='NOME DOCUMENTO')),
                ('created_doc', models.DateTimeField(auto_now_add=True)),
                ('update_doc', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='NOME DO PROJETO')),
                ('company', models.CharField(max_length=255)),
                ('pref_proj', models.CharField(max_length=30)),
                ('cod_proj', models.CharField(max_length=30)),
                ('comments', models.TextField()),
                ('created_proj', models.DateTimeField(auto_now_add=True)),
                ('update_proj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pageformat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_format', models.CharField(max_length=15, verbose_name='TIPO DE ARQUIVO')),
                ('created_fm', models.DateTimeField(auto_now_add=True)),
                ('update_fm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sheet', models.CharField(max_length=4, verbose_name='TIPO DE FOLHA')),
                ('created_pt', models.DateTimeField(auto_now_add=True)),
                ('update_pt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_status', models.CharField(max_length=50, verbose_name='STATUS')),
                ('created_st', models.DateTimeField(auto_now_add=True)),
                ('update_st', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, verbose_name='DISCIPLINA')),
                ('subject_cod', models.CharField(max_length=8)),
                ('created_sub', models.DateTimeField(auto_now_add=True)),
                ('update_sub', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255, verbose_name='NOME DO COLABORADOR')),
                ('emp_position', models.CharField(max_length=255, verbose_name='FUNÇÃO')),
                ('emp_contract', models.CharField(max_length=20, verbose_name='CONTRATO')),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/photos/', verbose_name='FOTO')),
                ('created_emp', models.DateTimeField(auto_now_add=True)),
                ('update_emp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='USUÁRIO')),
            ],
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_page', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT DOC')),
                ('qt_doc', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT HH')),
                ('cost_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CUSTO DOCUMENTO')),
                ('created_ct', models.DateTimeField(auto_now_add=True)),
                ('update_ct', models.DateTimeField(auto_now=True)),
                ('doc_name_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.doct', verbose_name='DOCUMENTO BASE')),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.pagesheet', verbose_name='TIPO PÁGINA')),
                ('proj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.myproject', verbose_name='PROJETO')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.subject', verbose_name='DISCIPLINA')),
            ],
        ),
    ]
