# Generated by Django 4.0.1 on 2022-01-18 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=12, verbose_name='AÇÃO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(max_length=5, verbose_name='TIPO DE DOCUMENTO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='NOME DOCUMENTO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='NOME DO PROJETO')),
                ('company', models.CharField(max_length=255, verbose_name='NOME DA EMPRESA')),
                ('pref_proj', models.CharField(max_length=30, verbose_name='PREFÍXO DO PROJETO')),
                ('cod_proj', models.CharField(max_length=30, verbose_name='CÓDIGO DO PROJETO')),
                ('comments', models.TextField(verbose_name='COMENTÁRIOS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pageformat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_format', models.CharField(max_length=15, verbose_name='TIPO DE ARQUIVO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sheet', models.CharField(max_length=4, verbose_name='TIPO DE FOLHA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_status', models.CharField(max_length=50, verbose_name='STATUS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, verbose_name='DISCIPLINA')),
                ('subject_cod', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255, verbose_name='NOME DO COLABORADOR')),
                ('emp_position', models.CharField(max_length=255, verbose_name='FUNÇÃO')),
                ('emp_contract', models.CharField(max_length=20, verbose_name='CONTRATO')),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/photos/', verbose_name='FOTO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUÁRIO')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentListProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(max_length=255, verbose_name='NOME DO DOCUMENTO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('doc_name_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.documentbase', verbose_name='DOCUMENTO BASE')),
                ('page_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.pageformat', verbose_name='FORMATO PÁGINA')),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.pagesheet', verbose_name='TIPO PÁGINA')),
                ('proj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.myproject', verbose_name='PROJETO')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.subject', verbose_name='DISCIPLINA')),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.doct', verbose_name='TIPO DE DOCUMENTO')),
            ],
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_page', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT PÁGINA')),
                ('qt_doc', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT DOC')),
                ('qt_hh', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT HH')),
                ('cost_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CUSTO DOCUMENTO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('doc_name_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.documentbase', verbose_name='DOCUMENTO BASE')),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.pagesheet', verbose_name='TIPO PÁGINA')),
                ('proj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.myproject', verbose_name='PROJETO')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.subject', verbose_name='DISCIPLINA')),
            ],
        ),
    ]
