# Generated by Django 4.0 on 2022-01-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='created_st',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='update_st',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='cotation',
            old_name='created_ct',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cotation',
            old_name='update_ct',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='doct',
            old_name='created_dt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='doct',
            old_name='update_dt',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='documentlist',
            old_name='created_doc',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='documentlist',
            old_name='update_doc',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='created_emp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='update_emp',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='myproject',
            old_name='created_proj',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='myproject',
            old_name='update_proj',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='pageformat',
            old_name='created_fm',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pageformat',
            old_name='update_fm',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='pagesheet',
            old_name='created_pt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pagesheet',
            old_name='update_pt',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='statusdoc',
            old_name='created_st',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='statusdoc',
            old_name='update_st',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='created_sub',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='update_sub',
            new_name='update_at',
        ),
        migrations.AddField(
            model_name='cotation',
            name='qt_hh',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT HH'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='qt_doc',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT DOC'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='qt_page',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='QT PÁGINA'),
        ),
    ]
