# Generated by Django 4.0.1 on 2022-01-08 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_rename_created_st_action_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotation',
            name='page_format',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proj.pageformat', verbose_name='FORMATO PÁGINA'),
            preserve_default=False,
        ),
    ]
