# Generated by Django 4.0.1 on 2022-01-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_cotation_page_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotation',
            name='page_format',
        ),
        migrations.AlterField(
            model_name='cotation',
            name='doc_name_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.documentlist', verbose_name='DOCUMENTO BASE'),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='cod_proj',
            field=models.CharField(max_length=30, verbose_name='CÓDIGO DO PROJETO'),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='comments',
            field=models.TextField(verbose_name='COMENTÁRIOS'),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='company',
            field=models.CharField(max_length=255, verbose_name='NOME DA EMPRESA'),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='pref_proj',
            field=models.CharField(max_length=30, verbose_name='PREFÍXO DO PROJETO'),
        ),
        migrations.CreateModel(
            name='DocumentListProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(max_length=255, verbose_name='NOME DO DOCUMENTO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('doc_name_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.documentlist', verbose_name='DOCUMENTO BASE')),
                ('page_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.pageformat', verbose_name='FORMATO PÁGINA')),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.pagesheet', verbose_name='TIPO PÁGINA')),
                ('proj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.myproject', verbose_name='PROJETO')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.subject', verbose_name='DISCIPLINA')),
                ('tipe_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.doct', verbose_name='TIPO DE DOCUMENTO')),
            ],
        ),
    ]
