# Generated by Django 4.0.1 on 2022-01-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_remove_cotation_page_format_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentList',
            new_name='DocumentBase',
        ),
    ]
