# Generated by Django 4.0.1 on 2022-01-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_rename_documentlist_documentbase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentlistproject',
            old_name='tipe_doc',
            new_name='type_doc',
        ),
    ]
